### ISSUE TITLE
Add FromName field

### ISSUE THREAD

**Issue by zubricks** [payloadcms/payload-plugin-form-builder#1]
> I was creating an HR form that I didn’t catch before but just got a request to update, and when I was in there doing the email confirmations, I just realized we don’t have the option for “From Name” on the email that goes to the user who fills out the form. We normally do something like “Hope Network Human Resources or Hope Network Transportation” for that, rather than just the email address

**Comment by jacobsfletch** [comment]
@zubricks turns out this was always possible. You just need use this format:

Example from: `Firstname Lastname <email@email.com>`
Example to: `{{firstName}} {{lastName}} <{{email}}`

I went ahead and added more descriptive placeholders for these two fields [in this commit](https://github.com/payloadcms/payload-plugin-form-builder/commit/07bc1b22a51e16b94fb53a1d349966eb8bbd962c):

![Screen Shot 2022-04-10 at 12 54 00 PM](https://user-images.githubusercontent.com/15735305/162630605-ba842116-aa50-44a7-be18-5ef8486eb1b8.jpg)
